name: Update README with activity

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: Shpota/github-activity-generator@master
        with:
          GITHUB_USER: Purvakhachane

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Update activity"
